#### Дано
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов

documents = [
{‘type’: ‘passport’, ‘number’: ‘2207 876234’, ‘name’: ‘Василий Гупкин’},
{‘type’: ‘invoice’, ‘number’: ‘11-2’, ‘name’: ‘Геннадий Покемонов’},
{‘type’: ‘insurance’, ‘number’: ‘10006’, ‘name’: ‘Аристарх Павлов’}
]

2.перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
‘1’: [‘2207 876234’, ‘11-2’],
‘2’: [‘10006’],
‘3’: []
}

### Задание 1
#### Пункт 1. Пользователь по команде “p” может узнать владельца документа по его номеру
Примеры работы:

1:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

2:

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [1]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
#documents[1]['name']
for a in documents:
    print(a['number'])

2207 876234
11-2
10006


In [22]:
def find_id (person):
    owner = []
    komanda = input('Введите команду: ')
    dok_nr = input('Введите номер документа: ')
    if komanda == 'p':
        for info in person:
            if dok_nr == info['number']:
                #print('Владелец документа ' , info['name'])
                owner.append(info['name'])
            else:
                #print('Документа в базе нет')
                pass
        print ('Владелец документа' , owner)
    elif komanda != 'p':
        print('Введите правильную команду')
    else:
        print('Документа в базе нет')
    

                


In [23]:
find_id(documents)

Введите команду: p
Введите номер документа: 10006
Владелец документа ['Аристарх Павлов']


### Комментарий
Я попробовал двумя способами, в т.ч. через цикл while, не получается запросить у юзера новый инпут в случае неверной команды.
 А так. вроде функция функционируеет. 

#### Пункт 2. 
Пользователь по команде “s” может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [24]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}


In [4]:
def find_id (shelf_nr):
    komanda = input('Введите команду: ')
    dok_nr = input('Введите номер документа: ')
    if komanda == 's':
        for a, b in shelf_nr.items():
            if dok_nr in shelf_nr[a]:
                print('ваш документ на полке ', a)
            else:
                pass
    else:
        print('неправильная команда')
   
        
        
find_id(directories)

Введите команду: s
Введите номер документа: 11-2
ваш документ на полке  1


#### Пункт 3. 
Пользователь по команде “l” может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [17]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}

    
        

In [18]:
def info(documents, directories):
    for shelf, content in directories.items():
        for doc in documents:
            if doc['number'] in content :
                print(doc,' Полка хранения документа № ', shelf)

info(documents, directories)

{'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}  Полка хранения документа №  1
{'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}  Полка хранения документа №  1
{'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}  Полка хранения документа №  2


#### Пункт 4. 
Пользователь по команде “as” может добавить новую полку

In [111]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0'], '99': ['99']}
type(directories)

dict

In [112]:
def polki(add_polka):
    komanda = input('введите команду для добавления плки  ')
    polka_nr = input('введите номер полки ')
    if komanda == 'ads':    
        for shelf, content in add_polka.items():
            if polka_nr in shelf:
                print('такая полка уже есть ')
            else:
                add_polka[polka_nr] = ''
                print('Полка нр ', polka_nr, ' успешно добавлена!!!')
                break
    else:
        print('введите правильную команду ')
    x = add_polka.keys()
    return print ('текущий перечень полок', x)


In [116]:
polki(directories)

введите команду для добавления плки  ads
введите номер полки 6
Полка нр  6  успешно добавлена!!!
текущий перечень полок dict_keys(['1', '2', '3', '99', '5', '6'])


### Пункт 5. 

Пользователь по команде “ds” может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3

In [117]:
def polka_out(polki_net):
    komanda = input('введите команду для добавления плки  ')
    polka_nr = input('введите номер полки ')
    if komanda != 'ds':
        print('введите правильную команду')
    else:
        if polka_nr not in polki_net.keys():
            print('такой полки нет')
        else:
            for shelf, content in polki_net.items():
                if polka_nr in shelf and content == '':
                    polki_net.pop(polka_nr)
                    print('полка под нр ', polka_nr, ' удалена')
                    break
                elif polka_nr in shelf and content != '':
                    print('на полке что-то есть удалять нельзя')
                else:
                    pass
    x = polki_net.keys()
    return print ('текущий перечень полок', x)

In [118]:
polka_out(directories)

введите команду для добавления плки  ds
введите номер полки 6
полка под нр  6  удалена
текущий перечень полок dict_keys(['1', '2', '3', '99', '5'])
