#### Дано
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов

documents = [
{‘type’: ‘passport’, ‘number’: ‘2207 876234’, ‘name’: ‘Василий Гупкин’},
{‘type’: ‘invoice’, ‘number’: ‘11-2’, ‘name’: ‘Геннадий Покемонов’},
{‘type’: ‘insurance’, ‘number’: ‘10006’, ‘name’: ‘Аристарх Павлов’}
]

2.перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
‘1’: [‘2207 876234’, ‘11-2’],
‘2’: [‘10006’],
‘3’: []
}

### Задание 1
#### Пункт 1. Пользователь по команде “p” может узнать владельца документа по его номеру
Примеры работы:

1:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

2:

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [1]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]


In [4]:
def who_is(person):
    while True:
        komanda = input('Введите команду: ')
        if komanda != 'p':
            print('Введите правильную команду')
        else:
            owner = []
            no_owner = 0
            dok_nr = input('Введите номер документа: ')
            for info in person:
                if dok_nr == info['number']:
                    owner.append(info['name'])
                    print('Владелец документа ' , owner)
                    break
                else:
                    no_owner += 1
            if no_owner == len(person):
                print('Такого док-та в базе нет ')
            else:
                pass
        break

In [5]:
who_is(documents)

Введите команду: p
Введите номер документа: 2207 876234
Владелец документа  ['Василий Гупкин']


#### Пункт 2. 
Пользователь по команде “s” может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [7]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}


In [12]:
def where_it(by_id):
    while True:
        komanda = input('Введите команду: ')
        if komanda != 's':
            print('Введите правильную команду')
        else:
            not_found = 0
            dok_nr = input('Введите номер документа: ')
            for a, b in by_id.items():
                if dok_nr in by_id[a]:
                    print('ваш документ на полке ', a)
                else:
                    not_found += 1
            if not_found == len(by_id):
                print('Документ не найден в базе')
            else:
                pass
        break

In [16]:
where_it(directories)

Введите команду: s
Введите номер документа: 11-2
ваш документ на полке  1


#### Пункт 3. 
Пользователь по команде “l” может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [22]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}
 
for doc in documents:
    print(doc['number'])

2207 876234
11-2
10006


In [29]:
def where_it(documents, directories):
    while True:
        komanda = input('Введите команду: ')
        if komanda != 'l':
            print('Введите правильную команду')
        else:
            show_all = []
            for shelf, content in directories.items():
                for doc in documents:
                    if doc['number'] in content :
                        combined_info = ('№: ', doc['number'], 'тип: ', doc['type'], 'владелец: ',
                                         doc['name'], ' Полка хранения документа ', shelf)
                        show_all.append(combined_info)
                        show_as_string = str(show_all)
            print(show_as_string.strip("'},{)(]['"))
        break

In [30]:
where_it(documents, directories)

Введите команду: l
№: ', '2207 876234', 'тип: ', 'passport', 'владелец: ', 'Василий Гупкин', ' Полка хранения документа ', '1'), ('№: ', '11-2', 'тип: ', 'invoice', 'владелец: ', 'Геннадий Покемонов', ' Полка хранения документа ', '1'), ('№: ', '10006', 'тип: ', 'insurance', 'владелец: ', 'Аристарх Павлов', ' Полка хранения документа ', '2


#### Пункт 4. 
Пользователь по команде “ads” может добавить новую полку

In [41]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']} 
        
        

In [42]:
def polki(add_polka):
    while True:
        komanda = input('Введите команду: ')
        if komanda != 'ads':
            print('Введите правильную команду')
        else:
            polka_nr = input('введите номер полки ')
            shelves = []
            more_shelves = []
            polka_count = 0
            for shelf in add_polka:
                shelves.append(shelf)
            if polka_nr in shelves:
                print('такая полка уже существует.Текущий перечень полок: ', shelves)
            else:
                directories.update({polka_nr :[]})
                polka_count += 1
            for x in directories:
                more_shelves.append(x)
            if polka_count == 1:
                print('Полка добавлена.Текущий перечень полок: ', more_shelves)
        break

In [56]:
polki(directories)

Введите команду: ads
введите номер полки 8
Полка добавлена.Текущий перечень полок:  ['1', '2', '3', '4', '5', '6', '7', '8']


In [57]:
directories

{'1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': ['0'],
 '4': [],
 '5': [],
 '6': [],
 '7': [],
 '8': []}

### Пункт 5. 

Пользователь по команде “ds” может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3

In [59]:
def polka_out(polka_remove):
    while True:
        komanda = input('Введите команду: ')
        if komanda != 'ds':
            print('Введите правильную команду')
        else:
            polka_nr = input('введите номер полки ')
            polki = []
            polki_net = []
            polka_count = 0
            checker = 0
            for x in polka_remove:
                polki.append(x)
            for shelf, content in polka_remove.items():
                if polka_nr == shelf:
                    if content == []:
                        polka_remove.pop(polka_nr)
                        polka_count += 1
                        break #ставлю чтобы не выдавало ошибку
                    else:
                        print('На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: ', polki)
                else:
                    checker += 1
            if checker == len(polki):
                print('такой полки нет')
            else:
                pass
            if polka_count == 1:
                for x in polka_remove:
                    polki_net.append(x)
                print('Полка удалена. Текущий перечень полок: ', polki_net)
        break

In [60]:
polka_out(directories)

Введите команду: ds
введите номер полки 8
Полка удалена. Текущий перечень полок:  ['1', '2', '3', '4', '5', '6', '7']
