#### Дано
Вам нужно помочь секретарю автоматизировать работу. Для этого нужно написать программу, которая будет на основе хранимых данных исполнять пользовательские команды.

Исходные данные имеют следующую структуру:

1. перечень всех документов

documents = [
{‘type’: ‘passport’, ‘number’: ‘2207 876234’, ‘name’: ‘Василий Гупкин’},
{‘type’: ‘invoice’, ‘number’: ‘11-2’, ‘name’: ‘Геннадий Покемонов’},
{‘type’: ‘insurance’, ‘number’: ‘10006’, ‘name’: ‘Аристарх Павлов’}
]

2.перечень полок, на которых хранятся документы (если документ есть в documents, то он обязательно должен быть и в directories)

directories = {
‘1’: [‘2207 876234’, ‘11-2’],
‘2’: [‘10006’],
‘3’: []
}

### Задание 1
#### Пункт 1. Пользователь по команде “p” может узнать владельца документа по его номеру
Примеры работы:

1:

Введите команду:
p

Введите номер документа:
10006

Результат:
Владелец документа: Аристарх Павлов

2:

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [1]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
#documents[1]['name']
#for a in documents:
    #print(len(a))

In [2]:
def find_id (person):
    owner = []
    no_owner = 0
    dok_nr = input('Введите номер документа: ')
    for info in person:
        if dok_nr == info['number']:
            #print('Владелец документа ' , info['name'])
            owner.append(info['name'])
            no_owner -= 0
            print('Владелец документа ' , owner)
        else:
            no_owner += 1
            #print(no_owner)
    if no_owner == len(person):
        print('Такого док-та в базе нет ')
    else:
        pass
        



    

In [6]:
komanda = input('Введите команду: ')
if komanda != 'p':
    print('Введите правильную команду')
else:
    find_id(documents)

Введите команду: p
Введите номер документа: 11-2
Владелец документа  ['Геннадий Покемонов']


### Комментарий
Тестировал много раз, сейчас работает код.
 
 Надеюсь ни чего не упустил.

#### Пункт 2. 
Пользователь по команде “s” может по номеру документа узнать на какой полке он хранится
Примеры работы:

Введите команду:
s

Введите номер документа:
10006

Результат:
Документ хранится на полке: 2

Введите команду:
p

Введите номер документа:
12345

Результат:
Документ не найден в базе

In [7]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}


In [25]:
def find_shelf(by_id):
    not_found = 0
    dok_nr = input('Введите номер документа: ')
    for a, b in by_id.items():
        if dok_nr in by_id[a]:
            print('ваш документ на полке ', a)
        else:
            not_found += 1
    if not_found == len(by_id):
        print('Документ не найден в базе')
    else:
        pass
    

In [27]:
komanda_s = input('Введите команду: ')
if komanda_s != 's':
    print('Введите правильную команду')
else:
    find_shelf(directories)

Введите команду: s
Введите номер документа: 2207 876234
ваш документ на полке  1


#### Пункт 3. 
Пользователь по команде “l” может увидеть полную информацию по всем документам
Пример работы:

Введите команду:
l

Результат:

№: 2207 876234, тип: passport, владелец: Василий Гупкин, полка хранения: 1
№: 11-2, тип: invoice, владелец: Геннадий Покемонов, полка хранения: 1
№: 10006, тип: insurance, владелец: Аристарх Павлов, полка хранения: 2


In [87]:
documents = [
    {'type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'},
    {'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, 
    {'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}
]
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']}
 
        

In [98]:
def info(documents, directories):
    show_all = []
    for shelf, content in directories.items():
        for doc in documents:
            if doc['number'] in content :
                combined_info = (doc,' Полка хранения документа № ', shelf)
                show_all.append(combined_info)
                show_as_string = str(show_all)
    print(show_as_string.strip("'}{)(]['"))

In [99]:
komanda_l = input('Введите команду: ')
if komanda_l != 'l':
    print('Введите правильную команду')
else:
    info(documents, directories)

Введите команду: l
type': 'passport', 'number': '2207 876234', 'name': 'Василий Гупкин'}, ' Полка хранения документа № ', '1'), ({'type': 'invoice', 'number': '11-2', 'name': 'Геннадий Покемонов'}, ' Полка хранения документа № ', '1'), ({'type': 'insurance', 'number': '10006', 'name': 'Аристарх Павлов'}, ' Полка хранения документа № ', '2


#### Пункт 4. 
Пользователь по команде “ads” может добавить новую полку

In [256]:
directories = {'1': ['2207 876234', '11-2'], '2': ['10006'], '3': ['0']} 
        
        

In [259]:
def polki(add_polka):
    polka_nr = input('введите номер полки ')
    shelves = []
    more_shelves = []
    polka_count = 0
    for shelf in add_polka:
        shelves.append(shelf)
    if polka_nr in shelves:
        print('такая полка уже существует.Текущий перечень полок: ', shelves)
    else:
        directories.update({polka_nr :['0']})
        polka_count += 1
    for x in directories:
        more_shelves.append(x)
    if polka_count == 1:
        print('Полка добавлена.Текущий перечень полок: ', more_shelves)

In [285]:
komanda_ads = input('Введите команду: ')
if komanda_ads != 'ads':
    print('Введите правильную команду')
else:
    polki(directories)

Введите команду: ads
введите номер полки 9
Полка добавлена.Текущий перечень полок:  ['1', '2', '3', '4', '5', '6', '7', '8', '9']


In [286]:
directories

{'1': ['2207 876234', '11-2'],
 '2': ['10006'],
 '3': ['0'],
 '4': ['0'],
 '5': ['0'],
 '6': ['0'],
 '7': ['0'],
 '8': ['0'],
 '9': ['0']}

### Пункт 5. 

Пользователь по команде “ds” может удалить существующую полку из данных (только если она пустая)
Примеры работы:

Введите команду:
ds

Введите номер полки:
3
Результат:
Полка удалена. Текущий перечень полок: 1, 2.

Введите команду:
ds

Введите номер полки:
1
Результат:
На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: 1, 2, 3.

Введите команду:
ds

Введите номер полки:
4
Результат:
Такой полки не существует. Текущий перечень полок: 1, 2, 3

In [276]:
def polka_out(polka_remove):
    polka_nr = input('введите номер полки ')
    polki = []
    polki_net = []
    polka_count = 0
    checker = 0
    for x in polka_remove:
        polki.append(x)
    for shelf, content in polka_remove.items():
        if polka_nr == shelf:
            if content == ['0']:
                polka_remove.pop(polka_nr)
                polka_count += 1
                break #ставлю чтобы не выдавало ошибку
            else:
                print('На полке есть документа, удалите их перед удалением полки. Текущий перечень полок: ', polki)
        else:
            checker += 1
    if checker == len(polki):
        print('такой полки нет')
    else:
        pass
    if polka_count == 1:
        for x in polka_remove:
            polki_net.append(x)
        print('Полка удалена. Текущий перечень полок: ', polki_net) 


    



In [287]:
komanda_ads = input('Введите команду: ')
if komanda_ads != 'ds':
    print('Введите правильную команду')
else:
    polka_out(directories)

Введите команду: ds
введите номер полки 9
Полка удалена. Текущий перечень полок:  ['1', '2', '3', '4', '5', '6', '7', '8']
